### ISSUE TITLE
Error 500 on admin panel

### ISSUE THREAD

**Issue by TDKDEV** [MineWeb/MineWebCMS#115]
Bonjour / Hello

Depuis que j'ai mis à jour mon cms il y a quelque semaines, j'ai plus accès au panel admin.
Voici l'erreur que j'obtient.
Cordialement & merci à toutes les personnes pouvant m'aider sur le sujet.
```2019-02-09 23:07:09 Error: [MissingTableException] Table server_cmds for model ServerCmd was not found in datasource default.
Exception Attributes: array (
  'table' => 'server_cmds',
  'class' => 'ServerCmd',
  'ds' => 'default',
)
Request URL: /admin
Stack Trace:
#0 /var/www/lib/Cake/Model/Model.php(3525): Model->setSource('server_cmds')
#1 /var/www/lib/Cake/Model/Model.php(2921): Model->getDataSource()
#2 /var/www/lib/Cake/Model/Model.php(2893): Model->_readDataSource('all', Array)
#3 /var/www/app/Controller/AdminController.php(87): Model->find('all')
#4 [internal function]: AdminController->admin_index()
#5 /var/www/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(AdminController), Array)
#6 /var/www/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(AdminController), Object(CakeRequest))
#8 /var/www/app/webroot/index.php(115): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}`

**Comment by KuroSenseii** [comment]
tout les réponse sont en message épingler sur le discord.
