### ISSUE TITLE
[BUG] Bug sur mineweb avec le HTTPS !

### ISSUE THREAD

**Issue by Junior007ytb** [MineWeb/MineWebCMS#225]
Bonjour

Mon ancien pseudo -> Junior007dj
Mon Ancien Site -> www.fondatoria.ovh

Mon soucie est que le site est fonctionnel en HTTP mais pas sécurisé et si je me met en HTTPS mon site a le theme tout blanc.
Ducoup j'avais utiliser cloudflare pour forcer le https et maintenant j'ai remplacer une ligne de code !
Sa me fait le même résultat qu'avant...

**<IfModule mod_rewrite.c>

   RewriteEngine on

   RewriteCond %{SERVER_PORT} 80

   RewriteRule (.*) https://%{HTTP_HOST}/%1 [R,L]

   RewriteRule    ^$ app/webroot/    [L]

   RewriteRule    (.*) app/webroot/$1 [L]

   RewriteCond %{HTTPS} off

</IfModule>**

Au début je croyais que c'etait lier au erreur de la console ( Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR -> animated.css)
Mais il a le même nombres d'errreur en http qu'en https, comment je pourrais afficher la page de mon site en http sur le https ?

 RAPPEL -> j'aimerais savoir comment faire pour que le site sois sécurisé et que le https fasse en sorte que je vois le théme, car a chaque fois que je passe en http mon theme saffiche puis en https un fond blanc. j'ai fais plein de rapport de github mais cloudflare n'arrange en rien sur le théme
[15:32]
MENTIONNER MOI si vous avez une soutions, j'attrend toutes réponse ! @Junior007ytb
![ovh](https://user-images.githubusercontent.com/68146441/94366355-fb5bd400-00d7-11eb-9806-3cb9a26c494d.PNG)
![http](https://user-images.githubusercontent.com/68146441/94366362-01ea4b80-00d8-11eb-8d2f-fd895d71b844.PNG)

**Comment by Junior007ytb** [comment]
up

**Comment by MaximeMichaud** [comment]
Il n'y a pas de problème du côté de SSL, du moins pas pour ta situation.
Et sur ton site, j'obtiens une erreur. MYSQL est manquant.
Et pour être en mesure de t'aider, je n'ai pas assez d'informations.
Ce que je suis persuadé, c'est que cela vient de ton côté. Flexible SSL fonctionne sur MineWeb.
Et nulle besoin de forcer le HTTPS.. car, il n'est pas là sur ton serveur, mais uniquement sur CF.

**Comment by Junior007ytb** [comment]
CF ? cloudflare ? si c'est ça, je les déja activer auparavant, mais le soucie n'est pas de forcer ou de le mettre en HTTPS mais que dés que je met en https j'ai fond blanc dans toutes les pages accueil compris comme si les thémes ou les images ne se voyent pas !

A pars ça, merci de la réponse ;)

**Comment by PHPierrre** [comment]
C'est possible de d'abord vider supprimer le contenu du dossier `/app/tmp/cache/` afin de mieux visualiser la situation ?

**Comment by MaximeMichaud** [comment]
> C'est possible de d'abord vider supprimer le contenu du dossier `/app/tmp/cache/` afin de mieux visualiser la situation ?

[MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Y'a pas de magie noire derrière.



> CF ? cloudflare ? si c'est ça, je les déja activer auparavant, mais le soucie n'est pas de forcer ou de le mettre en HTTPS mais que dés que je met en https j'ai fond blanc dans toutes les pages accueil compris comme si les thémes ou les images ne se voyent pas !
> 
> A pars ça, merci de la réponse ;)

Beaucoup de gens utilisent le flexible SSL avec MineWeb. Et pourtant, ils n'ont jamais eu de soucis.

**Comment by PHPierrre** [comment]
> [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
> Y'a pas de magie noire derrière. Sauf, cela n'est pas le même problème que l'issue.

D'accord il y a donc 2 problèmes cependant tant que nous n'avons pas vidé le cache, nous ne pouvons pas allez plus loin ni émettre d'autres hypothèses. 
C'est courant dans MineWeb que le simple fait d'effacer le cache règle un problème.

**Comment by MaximeMichaud** [comment]
> > [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
> > Y'a pas de magie noire derrière. Sauf, cela n'est pas le même problème que l'issue.
> 
> D'accord il y a donc 2 problèmes cependant tant que nous n'avons pas vidé le cache, nous ne pouvons pas allez plus loin ni émettre d'autres hypothèses.
> C'est courant dans MineWeb que le simple fait d'effacer le cache règle un problème.

Oui lorsque c'est un type d'erreur étant imprécis. Je suis sûr à 95% de la situation actuelle. Cela m'étonne plutôt que cela soit sur une issue. Bref,

**Comment by Junior007ytb** [comment]
Ok je rechange de CMS et je test ça !
merci de l'aide par avance !

**Comment by Junior007ytb** [comment]
`[PDOException] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fondato10002.configurations' doesn't exist
#0 /home/fondato/www/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /home/fondato/www/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Configu...', Array)
#2 /home/fondato/www/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Configu...', Array, Array)
#3 /home/fondato/www/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Configu...', Array)
#4 /home/fondato/www/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Configuration), Array)
#5 /home/fondato/www/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first', Array)
#6 /home/fondato/www/app/Model/Configuration.php(8): Model->find('first')
#7 /home/fondato/www/app/Model/Configuration.php(25): Configuration->getData()
#8 /home/fondato/www/app/Controller/AppController.php(105): Configuration->getKey('name')
#9 /home/fondato/www/lib/Cake/Error/ExceptionRenderer.php(103): AppController->__initConfiguration()
#10 /home/fondato/www/lib/Cake/Error/ErrorHandler.php(128): ExceptionRenderer->__construct(Object(PDOException))
#11 [internal function]: ErrorHandler::handleException(Object(PDOException))
#12 {main}
Try to remove files on directory /app/tmp/cache/`


Ducoup c'est un bug de base de donnée, car j'ai essayer de le reinstaller mais je peut même pas me connecter.
Je fais des manipulations et je vois si j'ai toujours le bug https

Si je peut avoir un support personnelle sa serais bien ;)
Discord: Junior007#2715

**Comment by PHPierrre** [comment]
> Je fais des manipulations

Lesquelles ? Avez-vous essayé de supprimer le contenu du dossier /app/tmp/ ?

> Je fais des manipulations et je vois si j'ai toujours le bug https

Quelle est l'adresse de votre site web ?

> Si je peut avoir un support personnelle sa serais bien ;)

C'est ce que nous faisons ici 😉

**Comment by Junior007ytb** [comment]
fondatoria.net

Manipulation, c'est-a-dire de supprimer le fichier cache ou tmp.
Mais la mon nouveau bug c'est que des que je me connecte sur le site je repasse en visiteur et je dois encore me reconnecter et sa fait sa a l'infinie !

Pour le support c'est que le https fait 1 an que j'ai ce soucie, donc sur le support mineweb discord c'est assez vague comme aide ou alors c'est pas ce que je recherche.

Je remercie quand même pour ce gentil support sur github c'est sympa =P

**Comment by PHPierrre** [comment]
Actuellement, j'ai une "Internal Server Error" ou erreur 500 sur votre site internet donc je ne peux pas constater par moi-même.

Par rapport au problème avec vos sessions, vous êtes chez OVH ?

**Comment by Junior007ytb** [comment]
oui

**Comment by PHPierrre** [comment]
Je vous donnerais une piste de résolution de votre problème un fois le premier ci-dessous résolu.

> Actuellement, j'ai une "Internal Server Error" ou erreur 500 sur votre site internet donc je ne peux pas constater par moi-même.

**Comment by Junior007ytb** [comment]
https://pastebin.com/rpzJWxf8

**Comment by PHPierrre** [comment]
Il faudrait tester de passer au moteur php-fpm vers phpcgi de ovh.

Trouvez cette ligne dans votre .ovhconfig : `app.engine=php` et remplacez php par `phpcgi`.

Plus d'infos ici : https://docs.ovh.com/fr/hosting/configurer-fichier-ovhconfig/

**Comment by wildmaster84** [comment]
Hey, i have had the same issue with some of my projects over the years and this is because of Cloud Flair using a proxy to hide your web servers ip.

To force https using .htaccess, paste the following code into your .htaccess file (/app/webroot/.htaccess)
`   RewriteCond %{HTTPS} off
    RewriteCond %{HTTP:X-Forwarded-Proto} !https
    RewriteCond %{HTTP:CF-Visitor} !https
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`

![image](https://user-images.githubusercontent.com/46942741/116824454-5bc45f80-ab58-11eb-8d97-9834d03f78c0.png)
