### ISSUE TITLE
Erreur interne,  veuillez réessayer [BUG] 

### ISSUE THREAD

**Issue by Basicroquette20** [MineWeb/MineWebCMS#230]
Bonjour lorsque je veut configurer mon compte administrateur, il y une erreur interne sans plus de précision quelqu'un a une idée?

Les logs:
```
2020-10-31 22:59:37 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'getKey' at line 1
Request URL: /
Stack Trace:
#0 /homepages/36/d848325126/htdocs/httpdocs/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /homepages/36/d848325126/htdocs/httpdocs/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('getKey', Array)
#2 /homepages/36/d848325126/htdocs/httpdocs/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('getKey', Array, Array)
#3 /homepages/36/d848325126/htdocs/httpdocs/lib/Cake/Model/Datasource/DboSource.php(648): DboSource->fetchAll('getKey', Array, Array)
#4 /homepages/36/d848325126/htdocs/httpdocs/lib/Cake/Model/Model.php(834): DboSource->query('getKey', Array, Object(AppModel))
#5 /homepages/36/d848325126/htdocs/httpdocs/app/Controller/AppController.php(105): Model->__call('getKey', Array)
#6 /homepages/36/d848325126/htdocs/httpdocs/app/Controller/AppController.php(58): AppController->__initConfiguration()
#7 /homepages/36/d848325126/htdocs/httpdocs/app/Controller/InstallController.php(9): AppController->beforeFilter()
#8 /homepages/36/d848325126/htdocs/httpdocs/lib/Cake/Event/CakeEventManager.php(244): InstallController->beforeFilter(Object(CakeEvent))
#9 /homepages/36/d848325126/htdocs/httpdocs/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#10 /homepages/36/d848325126/htdocs/httpdocs/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#11 /homepages/36/d848325126/htdocs/httpdocs/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(InstallController), Object(CakeRequest))
#12 /homepages/36/d848325126/htdocs/httpdocs/app/webroot/index.php(114): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

```

Quelqu'un a une solution svp?

**Comment by Eywek** [comment]
Essaye de vider /app/tmp
